name: "AccuKnox DAST Scanner"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

inputs:
  token:
    description: "API token for AccuKnox CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  target_url:
    description: "The URL of the web application to scan"
    required: true
  severity_threshold:
    description: "Minimum severity to fail the scan (LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  dast_scan_type:
    description: "DAST scan type: baseline or full-scan"
    required: false
    default: "baseline"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Prepare scan directory
      shell: bash
      run: |
        SCAN_DIR="/tmp/scan-dir"
        mkdir -p "$SCAN_DIR"
        chmod 777 "$SCAN_DIR"
        echo "Scan directory ready at $SCAN_DIR"

    - name: Download AccuKnox ASPM Scanner
      shell: bash
      run: |
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o /tmp/accuknox-aspm-scanner
        chmod +x /tmp/accuknox-aspm-scanner
        echo "AccuKnox ASPM Scanner ready at /tmp/accuknox-aspm-scanner"

    - name: Install DAST tool
      shell: bash
      run: |
        /tmp/accuknox-aspm-scanner tool install --type dast

    - name: Run DAST scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        TARGET_URL: ${{ inputs.target_url }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e
        cd /tmp/scan-dir

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: ACCUKNOX_TOKEN, ACCUKNOX_LABEL, ACCUKNOX_ENDPOINT, and TARGET_URL must be set!"
          exit 1
        fi

        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Properly escape entire command as a single string
        DAST_CMD="--target-url '$TARGET_URL' --severity-threshold '$SEVERITY_THRESHOLD' --dast-scan-type '$DAST_SCAN_TYPE'"

        echo "Running AccuKnox DAST scan..."
        /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$DAST_CMD" --container-mode
