name: "AccuKnox DAST Scan"

description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application using the ASPM Scanner."

branding:
  icon: "shield"
  color: "darkblue"

inputs:
  ACCUKNOX_TOKEN:
    description: "API token for AccuKnox CSPM Console"
    required: true
  ACCUKNOX_LABEL:
    description: "Label for scan results in AccuKnox SaaS"
    required: true
  ACCUKNOX_ENDPOINT:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  TARGET_URL:
    description: "Target web application URL to scan"
    required: true
    default: "https://juice-shop.herokuapp.com/"
  DAST_SCAN_SCRIPT:
    description: "DAST scan script (zap-baseline.py or zap-fullscan.py)"
    required: false
    default: "zap-baseline.py"
  SOFT_FAIL:
    description: "Do not fail the pipeline if vulnerabilities are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Prepare Scan Directory
      shell: bash
      run: |
        SCAN_DIR="/tmp/scan-dir"
        mkdir -p "$SCAN_DIR"
        chmod 777 "$SCAN_DIR"
        echo "Scan directory ready at $SCAN_DIR"

    - name: Install AccuKnox ASPM Scanner
      shell: bash
      run: |
        echo "Installing AccuKnox ASPM scanner..."
        pip install https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox_aspm_scanner-0.13.4-py3-none-any.whl --break-system-packages
        echo "✅ ASPM scanner installed"

    - name: Run DAST Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.ACCUKNOX_TOKEN }}
        ACCUKNOX_LABEL: ${{ inputs.ACCUKNOX_LABEL }}
        ACCUKNOX_ENDPOINT: ${{ inputs.ACCUKNOX_ENDPOINT }}
        TARGET_URL: ${{ inputs.TARGET_URL }}
        DAST_SCAN_SCRIPT: ${{ inputs.DAST_SCAN_SCRIPT }}
        SOFT_FAIL: ${{ inputs.SOFT_FAIL }}
        DEBUG: "TRUE"
      run: |
        set -e
        cd /tmp/scan-dir

        # Prepare soft-fail argument
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Validate required secrets
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: ACCUKNOX_TOKEN, ACCUKNOX_LABEL, ACCUKNOX_ENDPOINT, and TARGET_URL must be set!"
          exit 1
        fi

        # Build DAST scan command
        ARGS="$DAST_SCAN_SCRIPT -t $TARGET_URL -I"
        echo "👉 Running DAST scan..."
        echo "/usr/local/bin/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command \"$ARGS\" --container-mode"

        accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$ARGS" --container-mode
        cd -
