name: "AccuKnox DAST Scanner"

on:
  workflow_dispatch:

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: "http://testphp.vulnweb.com"
      SEVERITY_THRESHOLD: "HIGH"
      DAST_SCAN_TYPE: "baseline"
      SOFT_FAIL: "true"
      SCAN_DIR: "/tmp/scan-dir"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare scan directory
        run: |
          mkdir -p $SCAN_DIR
          chmod 777 $SCAN_DIR
          echo "Scan directory ready: $SCAN_DIR"

      - name: Download AccuKnox ASPM Scanner
        run: |
          curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o /tmp/accuknox-aspm-scanner
          chmod +x /tmp/accuknox-aspm-scanner
          echo "AccuKnox ASPM Scanner ready at /tmp/accuknox-aspm-scanner"

      - name: Install DAST tool
        run: |
          /tmp/accuknox-aspm-scanner tool install --type dast

      - name: Run DAST Scan
        run: |
          cd $SCAN_DIR

          SOFT_FAIL_ARG=""
          if [ "$SOFT_FAIL" = "true" ]; then
            SOFT_FAIL_ARG="--softfail"
          fi

          # **Build full DAST command as a single string**
          DAST_CMD="zap.sh -t $TARGET_URL -s $SEVERITY_THRESHOLD -S $DAST_SCAN_TYPE"

          echo "Running AccuKnox DAST scan..."
          echo "/tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command \"$DAST_CMD\" --container-mode"
          
          /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$DAST_CMD" --container-mode
