name: "AccuKnox DAST Scanner"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

inputs:
  token:
    description: "API token for AccuKnox CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  target_url:
    description: "The URL of the web application to scan"
    required: true
  severity_threshold:
    description: "Minimum severity to fail the scan (LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  dast_scan_type:
    description: "DAST scan type: baseline or full-scan"
    required: false
    default: "baseline"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Install AccuKnox ASPM Scanner
      run: |
        echo "Downloading AccuKnox ASPM scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o /tmp/accuknox-aspm-scanner
        chmod +x /tmp/accuknox-aspm-scanner
        echo "ASPM scanner ready at /tmp/accuknox-aspm-scanner"
      shell: bash

    - name: Prepare scan directory
      run: |
        mkdir -p /tmp/scan-dir
        chmod 777 /tmp/scan-dir
        echo "Scan directory ready at /tmp/scan-dir"
      shell: bash

    - name: Install AccuKnox DAST tool
      run: |
        echo "Installing AccuKnox DAST tool..."
        /tmp/accuknox-aspm-scanner tool install --type dast
      shell: bash

    - name: Run AccuKnox DAST Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        TARGET_URL: ${{ inputs.target_url }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e
    
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: token, label, endpoint, and target_url must be provided!"
          exit 1
        fi
    
        cd /tmp/scan-dir
    
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi
    
        # Build scanner command arguments correctly
        CMD_ARGS="--target-url $TARGET_URL"
        [ -n "$SEVERITY_THRESHOLD" ] && CMD_ARGS="$CMD_ARGS --severity-threshold $SEVERITY_THRESHOLD"
        [ -n "$DAST_SCAN_TYPE" ] && CMD_ARGS="$CMD_ARGS --dast-scan-type $DAST_SCAN_TYPE"
    
        echo "Running AccuKnox DAST scan..."
        echo "/tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command '$CMD_ARGS' --container-mode"
        /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$CMD_ARGS" --container-mode
    
        cd -
