name: "AccuKnox DAST Scanner"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

inputs:
  token:
    description: "API token for AccuKnox CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  target_url:
    description: "The URL of the web application to scan"
    required: true
  severity_threshold:
    description: "Minimum severity to fail the scan (LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  dast_scan_type:
    description: "DAST scan type: baseline or full-scan"
    required: false
    default: "baseline"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: true

runs:
  using: "composite"
  steps:

    # Step 1: Create temporary scan directory
    - name: Prepare scan directory
      run: |
        export SCAN_DIR="/tmp/scan-dir"
        mkdir -p "$SCAN_DIR"
        chmod a+w "$SCAN_DIR"
        echo "Scan directory created at $SCAN_DIR"
      shell: bash

    # Step 2: Ensure ZAP folder exists
    - name: Prepare ZAP output directory
      run: |
        ZAP_DIR="$HOME/.local/bin/accuknox/dast/zap"
        mkdir -p "$ZAP_DIR"
        chmod a+w "$ZAP_DIR"
        echo "DAST output directory ready: $ZAP_DIR"
        ls -la "$ZAP_DIR"
      shell: bash

    # Step 3: Run DAST scan
    - name: Run AccuKnox DAST Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        TARGET_URL: ${{ inputs.target_url }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e

        # Validate required inputs
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: token, label, endpoint, and target_url must be provided!"
          exit 1
        fi

        # Download AccuKnox ASPM Scanner
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        # Install DAST tool
        echo "Installing AccuKnox DAST tool..."
        ./accuknox-aspm-scanner tool install --type dast

        # Handle soft fail
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Build the command string
        CMD_ARGS="--target-url $TARGET_URL"
        [ -n "$SEVERITY_THRESHOLD" ] && CMD_ARGS="$CMD_ARGS --severity-threshold $SEVERITY_THRESHOLD"
        [ -n "$DAST_SCAN_TYPE" ] && CMD_ARGS="$CMD_ARGS --dast-scan-type $DAST_SCAN_TYPE"

        # Run DAST scan
        echo "Running AccuKnox DAST scan..."
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$CMD_ARGS"
