name: "AccuKnox DAST Scanner"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

inputs:
  token:
    description: "API token for AccuKnox CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  target_url:
    description: "The URL of the web application to scan"
    required: true
  severity_threshold:
    description: "Minimum severity to fail the scan (LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  dast_scan_type:
    description: "DAST scan type: baseline or full-scan"
    required: false
    default: "baseline"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Prepare scan directory
      shell: bash
      run: |
        SCAN_DIR="/tmp/scan-dir"
        mkdir -p "$SCAN_DIR"
        chmod 777 "$SCAN_DIR"
        echo "Scan directory ready at $SCAN_DIR"

    - name: Download AccuKnox ASPM Scanner
      shell: bash
      run: |
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o /tmp/accuknox-aspm-scanner
        chmod +x /tmp/accuknox-aspm-scanner
        echo "AccuKnox ASPM Scanner ready at /tmp/accuknox-aspm-scanner"

    - name: Install DAST tool
      shell: bash
      run: |
        /tmp/accuknox-aspm-scanner tool install --type dast

    - name: Run DAST scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ secrets.ACCUKNOX_TOKEN }}
        ACCUKNOX_LABEL: ${{ secrets.ACCUKNOX_LABEL }}
        ACCUKNOX_ENDPOINT: ${{ secrets.ACCUKNOX_ENDPOINT }}
        TARGET_URL: "http://testphp.vulnweb.com"
        SEVERITY_THRESHOLD: "HIGH"
        DAST_SCAN_TYPE: "baseline"
        SOFT_FAIL: "true"
        SCAN_DIR: "/tmp/scan-dir"
      run: |
        set -e
        cd "$SCAN_DIR"

        # Validate required inputs
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: token, label, endpoint, and target_url must be provided!"
          exit 1
        fi

        # Prepare softfail flag
        SOFT_FAIL_ARG=""
        SOFT_FAIL_CLEAN="${SOFT_FAIL//[$'\t\r\n ']}"
        if [ "$SOFT_FAIL_CLEAN" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Build scanner arguments properly
        SCANNER_ARGS="--target-url \"$TARGET_URL\""
        [ -n "$SEVERITY_THRESHOLD" ] && SCANNER_ARGS="$SCANNER_ARGS --severity-threshold \"$SEVERITY_THRESHOLD\""
        [ -n "$DAST_SCAN_TYPE" ] && SCANNER_ARGS="$SCANNER_ARGS --dast-scan-type \"$DAST_SCAN_TYPE\""

        echo "Running AccuKnox DAST scan..."
        echo "Command: /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast $SCANNER_ARGS --container-mode"

        # Run the scan using eval to properly handle arguments
        eval /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast $SCANNER_ARGS --container-mode
