name: "AccuKnox DAST Scanner"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

inputs:
  token:
    description: "API token for AccuKnox CSPM Console"
    required: true
  label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  endpoint:
    description: "CSPM Console endpoint URL"
    required: true
    default: "https://cspm.demo.accuknox.com"
  target_url:
    description: "The URL of the web application to scan"
    required: true
  severity_threshold:
    description: "Minimum severity to fail the scan (e.g., LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  dast_scan_type:
    description: "DAST scan type: baseline or full-scan"
    required: false
    default: "baseline"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Download AccuKnox ASPM Scanner
      shell: bash
      run: |
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o /tmp/accuknox-aspm-scanner
        chmod +x /tmp/accuknox-aspm-scanner

    - name: Install DAST tool
      shell: bash
      run: |
        /tmp/accuknox-aspm-scanner tool install --type dast

    - name: Run DAST scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        TARGET_URL: ${{ inputs.target_url }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e

        # Pick correct ZAP script
        if [ "$DAST_SCAN_TYPE" = "full-scan" ]; then
          SCRIPT="zap-fullscan.py"
        else
          SCRIPT="zap-baseline.py"
        fi

        # Soft fail flag
        SOFT_FAIL="${SOFT_FAIL,,}"   # to lowercase
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Validate inputs
        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$TARGET_URL" ]; then
          echo "ERROR: token, label, endpoint, and target_url must be set!"
          exit 1
        fi

        # Build ZAP command string
        CMD="$SCRIPT -t $TARGET_URL -s $SEVERITY_THRESHOLD"

        echo "👉 Running DAST with command:"
        echo "/tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command \"$CMD\" --container-mode"

        /tmp/accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$CMD" --container-mode
